# {% set data = load_setup_py_data() %}

# package:
#   name: adlfs
  
#   version: {{ data['version'] }}

# source:
#   path: ..

# build:
#   # If the installation is complex, or different between Unix and Windows, use
#   # separate bld.bat and build.sh files instead of this key.  Add the line
#   # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
#   # "skip: True  # [not win]" to limit to Windows.
#   script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
#   noarch: python
#   build: 0
  
  

# requirements:
#   build:
#     - python
#     - setuptools
#   run:
#     - python
#     # dependencies are defined in setup.py
#     {% for dep in data['install_requires'] %}
#     - {{ dep.lower() }}
#     {% endfor %}
#     {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}

# test:
#   source_files:
#     - tests
#   requires:
#     - pytest
#     - pytest-cov
#     - pytest-docker-compose
#   commands:
#     - pytest --docker-compose=tests/docker-compose.yaml --docker-compose-no-build tests

# about:
#   home: https://github.com/dask/adlfs
#   summary: fsspec-compatible Azure Datake and Azure Blob Storage access
#   license: {{ data.get('license') }}
#   license_file: LICENSE.txt
